language: c
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - sudo sh ./apt.postgresql.org.sh
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main $PGVERSION >> /etc/apt/sources.list.d/pgdg.list"
env:
  - PGVERSION=11
  - PGVERSION=10
  - PGVERSION=9.6
  - PGVERSION=9.5
  - PGVERSION=9.4
  - PGVERSION=9.3
  - PGVERSION=9.2

  - PGVERSION=11 TARGET='set-test-upgrade test'
  - PGVERSION=10 TARGET='set-test-upgrade test'
  - PGVERSION=9.6 TARGET='set-test-upgrade test'
  - PGVERSION=9.5 TARGET='set-test-upgrade test'
  - PGVERSION=9.4 TARGET='set-test-upgrade test'
  - PGVERSION=9.3 TARGET='set-test-upgrade test'
  - PGVERSION=9.2 TARGET='set-test-upgrade test'

script: bash ./pg-travis-test.sh
